Repository rh-ecosystem-edge/console-plugin-nvidia-gpu, pull requests merged in 2022-05, with the labels that each got.

#21 Added someone to the owners.
  OWNERS
Labels: approved, lgtm, needs-ok-to-test

#22 Update helm chart repo
  console-plugin-nvidia-gpu-0.1.0.tgz
  console-plugin-nvidia-gpu-0.2.1.tgz
  index.yaml
Labels: lgtm

#25 Address low and moderate security concerns
  Dockerfile
  default.conf
Labels: lgtm

#27 Fix Dockerfile build image
  Dockerfile
Labels: approved, lgtm

#29 Revert image to have s2i available
  Dockerfile
Labels: approved, lgtm

#30 Revert image to have s2i available
  Dockerfile
Labels: approved, lgtm

#31 Add OCP version compatibility info
  README.md
Labels: approved, lgtm

#17 MGMT-9263 Add new GPU Dashboard
  console-extensions.json
  locales/en/plugin__console-plugin-nvidia-gpu.json
  package.json
  src/components/GPUDashboard.css
  src/components/GPUDashboard.tsx
  src/components/GPUDashboardCard.tsx
  src/components/GPUDashboardCardGraphs.css
  src/components/GPUDashboardCardGraphs.tsx
  src/components/GPUDashboardCardInfo.css
  src/components/GPUDashboardCardInfo.tsx
  src/components/GPUDashboardGraphs.tsx
  src/components/GPUDropdown.css
  src/components/GPUDropdown.tsx
  src/components/GPUInfoCard.tsx
  src/components/GPUPods.tsx
  src/components/types.ts
  src/resources/index.ts
  src/resources/node.ts
  src/resources/pod.ts
  src/utils/gpuInfo.ts
  src/utils/gpuOperatorFeatureFlag.ts
  src/utils/prometheus.ts
  src/utils/utils.ts
  webpack.config.ts
  yarn.lock
Labels: approved, lgtm
